# Generated by Django 4.1.7 on 2023-03-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_id',
            new_name='profile_pic',
        ),
    ]
