# Generated by Django 4.1.7 on 2023-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_staff_id_faculty_notification_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_notification',
            name='f_name',
            field=models.TextField(default='None'),
        ),
    ]
