# Generated by Django 4.1.7 on 2023-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_faculty_notification_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
