# Generated by Django 4.1.7 on 2023-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_faculty_leave_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_leave',
            name='f_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
