# Generated by Django 4.1.7 on 2023-04-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_faculty_leave_f_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_leave',
            name='f_name',
        ),
    ]
